### ISSUE TITLE
installation error on Prestashop 1.7.7.1

### ISSUE THREAD

**Issue by revelation1975** [Invertus/saferpayofficial#10]
Hi I tried to install the module on
Prestashop 1.7.7.1
PHP: 7.3.26
MySQL: 5.7.32

I have two critical errors which lead to an "HTTP 500 Internal Server Error" page
With the debug we get the following errors:

**_CRITICAL                 22:59:41 | php | Fatal Compile Error: Declaration of  SaferPayOfficial::getContainer() must be compatible with  ModuleCore::getContainer():  Symfony\Component\DependencyInjection\ContainerInterface
INFO                 22:59:41 | php | User Deprecated: Implementing  "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface"  without the "reset()" method is deprecated since Symfony 3.4 and will be  unsupported in 4.0 for class  "Csa\Bundle\GuzzleBundle\DataCollector\GuzzleCollector".

CRITICAL                 22:59:41 | request | Uncaught PHP Exception  Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error:  Declaration of SaferPayOfficial::getContainer() must be compatible with  ModuleCore::getContainer():  Symfony\Component\DependencyInjection\ContainerInterface" at  xxxxx/modules/saferpayofficial/saferpayofficial.php  line 24_**

Please help me solve the problem
Thank you

**Comment by Quebert90** [comment]
Mind sharing if you have resolved the issue? I am facing the same error in 1.7.7.2.
