### ISSUE TITLE
Payment attempts failing

### ISSUE THREAD

**Issue by dsimunic** [Invertus/saferpayofficial#119]
We're seeing a number of failed payment attempts from PrestaShop  (`"ShopInfo":"PrestaShop_1.7.8.8:Invertus_1.1.3"`). Orders are listed with status of "Waiting for provisioning (not paid)".

The module log says "Initialize API Failed" and dumps a large JSON file:

```
{
  "RequestHeader": {
    "SpecVersion": "1.23",
    "RetryIndicator": "0",
    "ClientInfo": {
      "ShopInfo": "PrestaShop_1.7.8.8:Invertus_1.1.3"
    }
  },
  "ReturnUrl": {
    "Url": "/fr/module/saferpayofficial/return?cartId=C&secureKey=X&orderId=0&moduleId=M&selectedCard=-1&isBusinessLicence=0"
  },
  "Notification": {
    "SuccessNotifyUrl": "/fr/module/saferpayofficial/notify?success=1&cartId=C&orderId=0&secureKey=X",
    "FailNotifyUrl": "/fr/module/saferpayofficial/notify?success=1&cartId=C&orderId=0&secureKey=X"
  }
}
```

Note the `SuccessNotifyUrl` and `FailNotifyUrl` are identical, both having parameter `success=1`. Is that by design?

The web log shows this line:

`[01/Aug/2023:15:52:06 +0000] "GET /fr/module/saferpayofficial/fail?cartId=C&orderId=0&secureKey=X&moduleId=M HTTP/2.0" 302 0 "/fr/commande" "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"`

Note the `orderId=0`.

We could not identify where is this `/fail` url coming from; note it has the `moduleId` parameter like the `ReturnUrl` in the json dump. Neither Success nor FailNotifyUrl have that parameter. It seems it's a redirect from the 'order' page after the `POST` to `POST /fr/module/saferpayofficial/validation`. 

--- 
In addition, another failed payment on July 31 uses the same secureKey as an order from April(?!), generated by a module developed by CustomWeb (we uninstalled these modules a few weeks ago, so they were not present at the time of the failed order on Jul 31):

```
[04/Apr/2023:17:30:42 +0000] "GET /fr/confirmation-commande?id_cart=C&id_module=M&key=625a82... HTTP/2.0" 302 0 "/fr/module/saferpaycw/endpoint?cw_transaction_id=...

[31/Jul/2023:14:25:42 +0000] "GET /fr/module/saferpayofficial/notify?success=1&cartId=C&orderId=O&secureKey=625a82... HTTP/2.0" 200 37 "-"
```
These are the only uses of that secure key. Newer failed order used a different key, as do other requests.

How are these secure keys generated and stored? Do we need to clean up something in the database?

**Comment by justelis22** [comment]
Hi there @dsimunic,

It seems like there was an issue during the installation/upgrade process, as I can see that you are using the latest module version 1.1.3, which has an increased Spec. Version 1.32, although in your logs version 1.23 is mentioned.

The notification container was also removed until we upgrade the API to the latest 1.35 version, where it is starting to be used.

My suggestion would be to reset the module and check your database configuration table to see if the API version is correct - 1.32.

I will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Comment by dsimunic** [comment]
Thanks for your quick support. Indeed, reset/reinstall/clear caches made the order go through properly.

It remains to understand the `secureKey`: how was it possible that the same key got used from April from another module? Is this something that SaferPay provides during the request, or something the module should generate?

**Comment by justelis22** [comment]
@dsimunic,

Could you share temporary access to your shop for investigation? We would need FTP and Back Office credentials.
As I am not sure we will be able to recreate it from our side, so we would like to analyze your case to provide the answer.

Best Regards,
Invertus Support team.

**Comment by dsimunic** [comment]
Access to the production server is unfortunately not possible due to legal limitations.

However, we could copy the whole install folder for you into a private repository, together with designated settings from the database. Would that be of any help?

**Comment by justelis22** [comment]
@dsimunic,

Thanks for coming back to me!

Yes, that would be helpful as well, if that is not too much effort.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@dsimunic,

We were able to analyze the case without access, so it is not needed.

The secure key is shared between controllers (notify, etc) because in order we get the response, we want to validate if the response is still related to a specific cart - it is additional security. The secure key is created during customer registration, and it stays always the same for the same customer. It is used for all orders of this customer. So this is the reason why we have the same secure key - because two orders were placed by the same customer.

Let me know if you have any other questions!

Best Regards,
Invertus Support team.

**Comment by dsimunic** [comment]
Thanks, please keep the updates frequent.

It is a rather nasty lack of functionality: we have to contact customers to check if they canceled out of the flow or there was an issue. Happens probably 5-6 times a week, if not more.

This is killing us, the workload has gone through the roof.

**Comment by justelis22** [comment]
Hi there @dsimunic,

It seems like there are no pending questions in this issue. Perhaps it can be closed?

Best Regards,
Invertus Support team.

**Comment by dsimunic** [comment]
Hi closing with note that we'd like to be updated on progress with regards to the missing functionality. Can you please set up a tracking issue?

**Comment by justelis22** [comment]
Hello @dsimunic!

Let's keep the other issue open, and I will post any updates there.

Best Regards,
Invertus Support team.
