### ISSUE TITLE
The controller AdminSaferPayOfficialSettings is missing or invalid

### ISSUE THREAD

**Issue by Chrescht** [Invertus/saferpayofficial#124]
I am getting the error `The controller AdminSaferPayOfficialSettings is missing or invalid.`
when trying to configure the module v1.1.3.
Prestashop 8.1.1
php 8.1.23

**Comment by justelis22** [comment]
Hi there @Chrescht,

We will analyze this issue and get back to you as soon as possible.

**Comment by Chrescht** [comment]
> Hi there @Chrescht,
> 
> We will analyze this issue and get back to you as soon as possible.

Ok thanks, I edited my post, php version is 8.1.23.

**Comment by justelis22** [comment]
Hi there @Chrescht,
Thanks for waiting!

I have just tested the module on the same environment that you have described and it installed successfully.

I can see that you have mentioned version 1.1.3, although the latest version available is 1.1.5, so please try to install that one - https://github.com/Invertus/saferpayofficial/releases/tag/1.1.5

If you are still facing some issues, please send us FTP and back office credentials (to support@invertus.eu), and we will try to perform the installation from our side.

Best Regards,
Invertus Support team

**Comment by Chrescht** [comment]
Thank you. Are you saying I didn't have to pay for the module on Prestashop Marketplace?
I am still getting the same error, I'll send you the details.

**Comment by justelis22** [comment]
Hi @Chrescht,

I have replied to you via email.
The module is free here, but on the addons marketplace there is a payment set by PrestaShop, and we are not able to place Github links on the Addons marketplace page.

If you have any questions, let me know!

Best Regards,
Invertus Support team

**Comment by Chrescht** [comment]
Thanks, it got _fixed_ by resetting the module.
Many thanks.
