### ISSUE TITLE
Warning message when upgrading to 1.2.0

### ISSUE THREAD

**Issue by Djohel** [Invertus/saferpayofficial#152]
Hi, 

When we perform the upgrade or installation of the module with debug mode enabled, we encounter a warning message.
Maybe this "use Configuration" is not needed, removing it prevent from getting the message
![image](https://github.com/Invertus/saferpayofficial/assets/130928080/d78c5aaa-17be-4064-a423-1e3da4761940)

**Comment by justelis22** [comment]
Hi @Djohel,

Does the same issue happen when upgrading to the 1.2.1 version?
If so, please let me know which PrestaShop and PHP version are you using.

Best Regards,
Invertus Support team.

**Comment by Djohel** [comment]
same issue with 1.2.1 version 

PHP version : 7.4.33
Prestashop : 1.7.8.7

**Comment by justelis22** [comment]
Hi there @Djohel,

Can you share your PrestaShop and PHP versions? We were not able to recreate the issue in our environments, so this could be related to your environment.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Djohel, thank you for your patience and understanding.

We have prepared a beta release for version 1.2.2. It is available here - https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.2-beta

All of the issues should be fixed, however, we would appreciate it if you could install the module on your development store to verify this.

The release was tested by our QA department and this is the final version, if we don't receive any negative feedback, we will release the module officially next week.

Best Regards,
Invertus Support team

**Comment by justelis22** [comment]
Closing as the 1.2.2 is officially released now.
