### ISSUE TITLE
I can't disable payment methods in Prestashop 1.7.7.2

### ISSUE THREAD

**Issue by harutkerobyan** [Invertus/saferpayofficial#16]
When I tried to disable some payment methods ( https://prnt.sc/10zzu7r ) after click save I got this error:
( https://prnt.sc/10zzvhc )
"Oops... looks like an unexpected error occurred
Attempted to load class "SaferPayField" from the global namespace. Did you forget a "use" statement?
[Symfony\Component\Debug\Exception\ClassNotFoundException 0]"

and it didn't save changes. Can you solve this problem?

Thanks

**Comment by fabi86** [comment]
Same here

**Comment by Saimis777** [comment]
Hello!

Could you clarify if you are running the latest version of the module? 

Let me know!

--
Best regards,
Invertus Support team

**Comment by fabi86** [comment]
Yes, downloaded it yesterday :)

**Comment by yvannb** [comment]
Same issue on Prestashop 1.7.7.3 with the latest version on fresh install

**Comment by Saimis777** [comment]
Hello,

Could you also clarify for which payment methods does this happen? And are there no country restrictions for those payments?

--
Best regards,
Invertus Support team

**Comment by yvannb** [comment]
The error comes with any change on the "Payments" tab. There is no restrictions enable for Saferpay in the payment settings

**Comment by Saimis777** [comment]
Thank you.

We are investigating the issue further, I will keep you posted!

--
Best regards,
Invertus Support team

**Comment by brunostuder** [comment]
Hello!

Same problem here:

<img width="1381" alt="Capture d’écran 2021-04-06 à 15 16 01" src="https://user-images.githubusercontent.com/59470758/113718598-19406c00-96ed-11eb-9543-e32bacea6eb8.png">
<img width="764" alt="Capture d’écran 2021-04-06 à 15 15 23" src="https://user-images.githubusercontent.com/59470758/113718605-1ba2c600-96ed-11eb-82c7-ef5299d9c4e6.png">

Best,

**Comment by yvannb** [comment]
@Saimis777 can you indicate where to disable payment methods in files while waiting ?

**Comment by Saimis777** [comment]
Hello,

Could you guys list the Prestashop + PHP versions you are using? As I saw the initial request was with PS 1.7.7.2, yet we've tested on our test environments, and seems that there is no error disabling the payment method:
![image](https://user-images.githubusercontent.com/75423142/114043178-bab2f380-988e-11eb-8f8d-0fdf0c40e69b.png)

Could you also double check if it's 100 % that are no restrictions in this section here:
![image](https://user-images.githubusercontent.com/75423142/114043727-3876ff00-988f-11eb-9043-aa4514086fb8.png)

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Also, the "unofficial" method of disabling a payment method in case you are running in to the error is would be to log in to your database, find the table named prefix+"saferpay_payment" in there, you will find all of the payment methods, so you can either switch it to "0" or "1"

![image](https://user-images.githubusercontent.com/75423142/114046217-55accd00-9891-11eb-93a7-abb8fb7ba875.png)


--
Best regards,
Invertus Support team

**Comment by harutkerobyan** [comment]
> Hello,
> 
> Could you guys list the Prestashop + PHP versions you are using? As I saw the initial request was with PS 1.7.7.2, yet we've tested on our test environments, and seems that there is no error disabling the payment method:
> ![image](https://user-images.githubusercontent.com/75423142/114043178-bab2f380-988e-11eb-8f8d-0fdf0c40e69b.png)
> 
> Could you also double check if it's 100 % that are no restrictions in this section here:
> ![image](https://user-images.githubusercontent.com/75423142/114043727-3876ff00-988f-11eb-9043-aa4514086fb8.png)
> 
> --
> Best regards,
> Invertus Support team

Hi

PrestaShop-Version 1.7.7.2
PHP-Version 7.2.34

**Comment by SimonasB88** [comment]
Hello guys, some days has passed, are you still experiencing issues about disabling the payments?

—
Best Regards
Invertus Support Team

**Comment by brunostuder** [comment]
Hi,

Yes thank you, disable the payment methods from PHPmyAdmin.

By the way, we are experiencing a "issue", payment from **Twint and Postcard are only AUTHORIZED and not captured**, we have to capture them manually (so now ~30 payments can't be captured anymore...).

Do you know how to automatically capture these payments (the option in the setting page of the plugin is already enabled) ?

Best,

**Comment by SimonasB88** [comment]
Dear @brunostuder 

Could you please raise a separate issue regarding separate case, referring to this thread? And please include some screenshots or video-screen reproduction. Developers will check this out.

Thank you.

—
Best Regards
Invertus Support Team

**Comment by yvannb** [comment]
I haven't tried the latest version yet. When I run the command composer `install` --no-dev `--optimize-autoloader` 
 composer return `[ErrorException]
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? `

**Comment by yvannb** [comment]
For me on Prestashop 1.7.7.4 with PHP 7.4.16, the version of Saferpay 1.0.7 update from the last github version seems to work good. Enable and disable payment method works, no error on update.
Thanks Invertus Team

**Comment by SimonasB88** [comment]
@yvannb very great news!

If additional issues appear, please raise them separately, it won't be a mess in thread then.

—
Best Regards
Invertus Support Team

**Comment by Saimis777** [comment]
Hey,

Due to inactivity, I will close this issue for now, let me know if further help is needed!

--
Best regards,
Invertus Support team
