### ISSUE TITLE
Redirection error and unemptied cart issue after validated Twint payments

### ISSUE THREAD

**Issue by fscheibler** [Invertus/saferpayofficial#162]
**Saferpay Module v1.2.2**

Hello,

When a payment is made via Twint, the payment is validated by both Twint and Saferpay. However, instead of being redirected to a confirmation page, the customer is redirected back to their cart which remains full.

An error message indicates that the payment has failed, even though the order has been successfully created.

The redirection should lead to a confirmed order page instead of displaying a payment error with the cart still full.

Thank you in advance.

Florent

**Comment by justelis22** [comment]
Hello @fscheibler,

As we haven't received any answers, I will close the issue.

If you are still facing this issue, please let me know, and I will reopen it.

Best Regards,
Invertus Support team.

**Comment by norca1762** [comment]
Hi,

I'm having the same issue when using TWINT, Postfinance Pay, Credit/Debit Card.

I'm using the module for the first time (v1.2.2) on Prestashop 1.7.8.11

I made a reset to the module but same issue. 

Thank you in advance.

Arijan

**Comment by justelis22** [comment]
Hello there,

Our team has identified the issue and is currently working to have a beta release with a fix this week.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

We have prepared a new [1.2.3 beta release](https://github.com/Invertus/saferpayofficial/releases/tag/release-1.2.3-beta) with additional fixes.
Email sending issue was also resolved, thanks for sending the information to us.

If possible, please install it on your demo store and we will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Comment by norca1762** [comment]
Hi justelis22,

Thanks for your hardwork.

I installed the new release and it seems that the issue with the redirection error is solved.
In the other hand, another problem has appeared. I don't receive the order confirmation by email anymore.
As a customer, the order confirmation and Saferpay payment confirmation it's OK, but as a shop owner, we can only see the order when conncected in the prestashop BO.
Any idea?

________________________________
De : justelis22 ***@***.***>
Envoyé : mardi, 3 septembre 2024 14:05
À : Invertus/saferpayofficial ***@***.***>
Cc : norca1762 ***@***.***>; Comment ***@***.***>
Objet : Re: [Invertus/saferpayofficial] Redirection error and unemptied cart issue after validated Twint payments (Issue #162)


Hi there,

The 1.2.3 release if officially released and can be used.

If there is anything else, please let me know!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @norca1762,

Can you send some screenshots of the module configuration to our email at support@invertus.eu?

Also, to have a fully functioning email service you need to configure the native PrestaShop module called Mail Alert. Do you have it configured with the correct email address?

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
@norca1762,

Glad to help you and to see that you are finally able to use the module.

If there is anything else, please don't hesitate to contact us!

Best Regards,
Invertus Support team.
