### ISSUE TITLE
Order confirmation with Iframe

### ISSUE THREAD

**Issue by Djohel** [Invertus/saferpayofficial#163]
Upon testing the latest release 1.22, we've encountered a new issue related to the iframe functionality. Specifically, when processing payments, we are experiencing unexpected redirections into the iframe, whether it's encountering errors or successfully completing the transaction.
see below a screen of the order_conf in the iframe 
![iframe_confirmation](https://github.com/Invertus/saferpayofficial/assets/130928080/35a1ae58-823d-44aa-8024-3b08b4c401d8)

We conducted a test by removing the "Tools::redirect" line at line 67 in controllers/front/successIFrame.php, and it resolved the issue. While this may not be the optimal solution, it could provide a temporary workaround for resolving the problem when using iFrame solution.

**Comment by justelis22** [comment]
Hi there @Djohel,
Thanks for the details!

At the moment, if the business license is enabled, I would suggest keeping the custom forms active to avoid this behavior.
We have a task in your plans and this will be improved in future releases.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Djohel,

The beta with this fix is already available - https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.4-beta

If you have any feedback, I would highly appreciate it.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
The new version is live.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.
