### ISSUE TITLE
Field Access Token

### ISSUE THREAD

**Issue by deepseoCH** [Invertus/saferpayofficial#164]
Hi, thank you for your work and support.
I don't quite understand one of the fields in the v1.2.2 module which is “Field Access Token”. An indication above this field informs that the token can be found “in Saferpay Backoffice, navigate to Settings > Saferpay Fields Access Tokens. More information on Saferpay Fields preparation: here”
Looking at the saferpay.com back office I can't find any information about “Saferpay Fields Access Tokens”. When generating the API Username JSON, information is given about “HTTP Header: Authorization: Basic”. Is this the information we need to put in the “Field Access Token” field of the module? Thanks in advance for your help.

**Comment by justelis22** [comment]
Hi there @deepseoCH,

“Field Access Token” is provided with the [Saferpay Business license](https://docs.saferpay.com/home/master/licensing/licences-and-interfaces), which should be purchased additionally. To obtain this, I would highly suggest contacting the Saferpay team directly and they will be able to help you with the process.

You can use the module without the Field access token, simply some functionalities will not be available.

Let me know if you have additional questions!

Best Regards,
Invertus Support team.

**Comment by deepseoCH** [comment]
Hi, thank you for your answer. I'm having a problem with the module. The connection to SaferPay seems to work correctly, since the payment methods configured in the saferpay.com back office are updated in the prestahop module tab. A modification (addition/deletion) of a payment method on saferpay is automatically updated in the module. However, selected and activated payment methods are not displayed on the order page in the shopping tunnel. Any idea ? Thank you in advance.

**Comment by justelis22** [comment]
@deepseoCH,

Can you share some screenshots or video recordings explaining the issue?

If possible, please share access to your back office via email to support@invertus.eu, that will speed up the analysis.

Best Regards,
Invertus Support team.

**Comment by deepseoCH** [comment]
I've just sent all informations by mail. Thank you
