### ISSUE TITLE
Redirection error and unemptied cart issue

### ISSUE THREAD

**Issue by norca1762** [Invertus/saferpayofficial#165]
Hi,

I have just installed and configured the Saferpay v1.2.2 module (first installation) on version 1.7.8.11 of Prestashop.

After each order placed using the payment methods (TWINT, Postfinance Pay, Credit/Debit Card), the order is confirmed by Prestashop as well as Saferpay.

But on the other hand, instead of redirecting the customer to the confirmation page, the customer is redirected to their shopping cart (which always contains the products they purchased).

An error message indicates that the payment failed, even though the order and payment confirmation is indeed received.

Is there a known solution?

Thanks in advance

Arijan

**Comment by justelis22** [comment]
Hi @norca1762, thanks for waiting!

This seems to be a different issue than the one explained in your initial message. however, we will fix the issue with notifications to properly create orders when a payment is completed.

Once that is done, we will be able to see if these two issues are related.

I will keep you updated, if everything goes according to plan, we should release a beta this week.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

We have prepared a new [1.2.3 beta release](https://github.com/Invertus/saferpayofficial/releases/tag/release-1.2.3-beta) with additional fixes.

If possible, please install it on your demo store and we will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there,

The 1.2.3 release if officially released and can be used.

If there is anything else, please let me know!

Best Regards,
Invertus Support team.
