### ISSUE TITLE
Cannot override MyAccount.tpl in theme

### ISSUE THREAD

**Issue by Djohel** [Invertus/saferpayofficial#167]
In the hookDisplayCustomerAccount method line 348, the template path is currently set to:

$this->getLocalPath() . 'views/templates/hook/front/MyAccount.tpl'
This prevents us from being able to override the template. Instead, it should be set to:

'module:saferpayofficial/views/templates/hook/front/MyAccount.tpl'
This change would allow us to properly override the template as needed.

below the function changed : 
```
public function hookDisplayCustomerAccount()
    {
        $isCreditCardSaveEnabled =
            Configuration::get(\Invertus\SaferPay\Config\SaferPayConfig::CREDIT_CARD_SAVE);
        if (!$isCreditCardSaveEnabled) {
            return;
        }
        if (\Invertus\SaferPay\Config\SaferPayConfig::isVersion17()) {
            return $this->context->smarty->fetch(
                // $this->getLocalPath() . 'views/templates/hook/front/MyAccount.tpl'
                'module:saferpayofficial/views/templates/hook/front/MyAccount.tpl'
            );
        }

        return $this->context->smarty->fetch(
            // $this->getLocalPath() . 'views/templates/hook/front/MyAccount_16.tpl'
            'module:saferpayofficial/views/templates/hook/front/MyAccount_16.tpl'
        );
    }
```

Thanks !

**Comment by justelis22** [comment]
Hi there @Djohel,

The beta with this improvement is already available - https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.4-beta

If you have any feedback, I would highly appreciate it.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
The new version is live.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.
