### ISSUE TITLE
Race conditions ?

### ISSUE THREAD

**Issue by Aktarus006** [Invertus/saferpayofficial#169]
Hello,

We recently updated our website to Prestashop 8 and saferpay 1.2.2. Since then we faced some issues regarding orders,

At first, when creating order before authorization, some of them are stuck in 'Awaiting Saferpay Payment' or go from a 'Payment Completed By Saferpay' to 'Payment Authorized by Saferpay'. 

![image](https://github.com/Invertus/saferpayofficial/assets/20419262/a812a365-6d14-45b3-98bb-bb72441c3b66)

When I look at the Prestashop logs I can see an error message saying that the cart cannot be loaded or an order as already been made using this cart.

![image](https://github.com/Invertus/saferpayofficial/assets/20419262/59e549d9-c9e0-45e6-8d44-c733bfe52f6f)

So we tried to create orders after authorization. No more orders stucked in awaiting but the reference of the order is not set anymore to saferpay and some orders are authorized or captured by saferpay but they are not created by Prestashop at all.  In saferpay logs I can see that these orders return an error saying the Transaction is in wrong state.

Are the notify and return controllers making request at the same time ?

Did you already face the same issues ? Do you have any clue on how to solve this ?

Thanks for your help

**Comment by id-clic** [comment]
Same issue.

**Comment by Dedra-be** [comment]
i'm facing the same bug, wich is damn annoying.

**Comment by Arnaud104** [comment]
Keep me informed if u guys find a solution because this bug is a pain 😒

**Comment by justelis22** [comment]
Hi everyone,
Thank you for raising this topic I understand it is inconvenient.

We are currently working on the race condition issue and a way to improve the locking process.

You are correct, the notification and authorization could happen at the same time, thus we need to improve the lock to avoid these issues.

I will keep you updated, as soon as I have some news.

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @Aktarus006 @id-clic @Dedra-be @Arnaud104, thank you for your patience!

We are currently in the process of testing the changes.

Here you can find the 1.2.3 beta release with the fixes - https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.3-beta

As you can understand this is not an official release, but if you have a development shop, I would appreciate it if you could install the module and check if everything is working correctly.

There were a lot of edge cases that we have been facing, so we don't want to release the module with any bugs.

The official release should be done next week depending on your feedback! Thank you and I am eagerly waiting to hear from you.

Best Regards,
Invertus Support team.

**Comment by Aktarus006** [comment]
Hello @justelis22,

Thank you for your return... I just installed the beta you provided on my test environment.
Right out of the box, I face some issue... All my orders are currently stucked when on the return page. I have the message with Awaiting Payment Status but can't reach the confirmation page.

The orders are well captured by Saferpay but in my Prestashop back office they still have the awaiting status.
When I look at the logs though I can see "CAPTURED" or "AUTHORIZED" appearing several times.

Maybe some of our modules are interfering during the update of the status? It's hard to say... Unfortunately I won't have much time to test or investigate deeper since I will be off at the end of the week and till the end of the month.

I'll try again when I come back !

**Comment by justelis22** [comment]
Hi there,

We did a second beta of the 1.2.3 release, fixed a few issues, and refactored the code. You can find it here - https://github.com/Invertus/saferpayofficial/releases/tag/v1.2.3-beta

Your feedback is highly appreciated!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there everyone, thank you for your patience.

The release 1.2.3 is live and available for download. The reported issues have been fixed and the standard flow should work without any issues.
In the upcoming release we will fix issues with the iframe as it is currently not fully working.

Best Regards,
Invertus Support team.
