### ISSUE TITLE
PrestaShop V8+ compatibility

### ISSUE THREAD

**Issue by herrnesto** [Invertus/saferpayofficial#177]
Hello, when can we await compatibility with newer versions of PrestaShop?

**Comment by justelis22** [comment]
Hi there @herrnesto,

The 1.2.3 version will have compatibility with the latest 8.1.x PS versions.

Currently, our full focus is set to preparation for this version release and we should have the second prerelease ready this week.

I will keep you updated!

Best Regards,
Invertus Support team.

**Comment by herrnesto** [comment]
Hey, that's great news. Thanks for keeping it updated!
