### ISSUE TITLE
Email sent 3 times

### ISSUE THREAD

**Issue by voldardard** [Invertus/saferpayofficial#185]
Hello,
Following lasts errors we had with module 1.22 with prestashop 8+, we had to use the beta version 1.23 to get working our prestashop. 2 days of debugging to find out the problem, in the database. And even by reinstalling the module, the database table for saferpay where not correctly created.
Now it seems to work, but we have another problem related to the saferpay module. At each order confirmation. "Payment completed by saferpay" we receive 3 times emails for the merchant:
![image](https://github.com/user-attachments/assets/442a2c9c-11a4-406a-81bf-5182396c63b6)

In the "Ps mail alert" module we have one address set (this one is a test address):
![image](https://github.com/user-attachments/assets/d588eeaa-d1fa-49a8-9962-9acb79cc3679)

And in the SaferPay module if I uncheck the box to send mail on authorization we don't receive any emails for the merchant. And if I check it we receive it 3 time:
![image](https://github.com/user-attachments/assets/ad67590e-af09-488f-96e4-659bc508f38b)

And on the order side:
![image](https://github.com/user-attachments/assets/f5a1548a-9058-4ad9-b6ed-6ee864fadcac)

On the customers side,  it is ok, and the customers receive the emails they should receive as normally.

Has anyone encounteer this issue with SaferPay module in 1.23 with emails sent to the merchants 3 times ?

Here the PS logs related to the order:
![image](https://github.com/user-attachments/assets/234b8667-d00d-405f-80a4-8d61a295e716)
There is no errors logs related in the saferpay module

Here the mails logs related (8h04 is with the box checked in the saferpay module and 07h58 with the box unchecked in the saferpay module):
![image](https://github.com/user-attachments/assets/f729b472-8224-449d-a362-68dd7e8bf8b9)

Thanks for your help by advance :)

Does anyone know, when the 1.23 will be stable ?

**Comment by justelis22** [comment]
Hi there @voldardard, thanks for waiting!

We are continuously working on and testing the 1.2.3 version.

As soon as we have finalized the release and fixed the issues, it will be officially release.

I will keep you updated!

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @voldardard,

We have prepared a new [1.2.3 beta release](https://github.com/Invertus/saferpayofficial/releases/tag/release-1.2.3-beta) with additional fixes.
Email sending issue was also resolved, thanks for sending the information to us.

If possible, please install it on your demo store and we will be waiting for your feedback!

Best Regards,
Invertus Support team.

**Comment by voldardard** [comment]
Hello

Thank you for your quick response. 

We could install successfully this new version of 1.2.3 release and it corrected all of our problems. The emails to the merchant are now sent only one time, installation was successfull without needing to adapt the database shema and with did not encounter errors for the moment. As the customer was annoyed by these problem, we also installed it in production and it seems to work well too!

Again, thank you ;)

Best regards

Mathias Brugger
