### ISSUE TITLE
Fail to execute command to install module

### ISSUE THREAD

**Issue by MLK57** [Invertus/saferpayofficial#19]
Hello, 

I tried to follow the installation steps but got this error.

"saferpayofficial php composer.phar install --no-dev --optimize-autoloader
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
The authenticity of host 'bitbucket.org (2406:da00:ff00::6b17:d1f5)' can't be established.
RSA key fingerprint is SHA256:zzXQOXSRBEiUtuE8AikJYKwbHaxvSc0ojez9YXaGp1A.
Are you sure you want to continue connecting (yes/no)? yes

                                                                               
  [RuntimeException]                                                           
  Failed to execute git clone --mirror -- 'git@bitbucket.org:invertus/integra  
  tion-test-suite.git' '/home/ben/.cache/composer/vcs/git-bitbucket.org-inver  
  tus-integration-test-suite.git/'                                             
                                                                               
  Cloning into bare repository '/home/ben/.cache/composer/vcs/git-bitbucket.o  
  rg-invertus-integration-test-suite.git'...                                   
  Warning: Permanently added 'bitbucket.org,2406:da00:ff00::6b17:d1f5' (RSA)   
  to the list of known hosts.                                                  
  git@bitbucket.org: Permission denied (publickey).                            
  fatal: Could not read from remote repository.                                
                                                                               
  Please make sure you have the correct access rights                          
  and the repository exists.                                                   
                                                                             "

Someone can help me ?

**Comment by Saimis777** [comment]
Hi @MLK57 ,

Could you clarify if you are using MAC/Linux/Windows, when installing Composer?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by MLK57** [comment]
Hi @Saimis777 ,

I use Linux (Ubuntu) ! :)

**Comment by Alfr3d** [comment]
Hello @MLK57 ,
Maybe you can describe the step-by-step process of installing the module? 
For example:
![image](https://user-images.githubusercontent.com/37298732/117970774-b9636380-b331-11eb-8691-41c9a613b3bf.png)
![image](https://user-images.githubusercontent.com/37298732/117970940-f3346a00-b331-11eb-8d7b-75caabd943bb.png)
.
.
.
![image](https://user-images.githubusercontent.com/37298732/117971017-09422a80-b332-11eb-9fef-79406175a1cd.png)

Also would be nice, if you tell us which composer version do you use :) 

Best regards.

**Comment by MLK57** [comment]
Hey !

I clone the repo and try to execute the command..

Some screenshot here : 
![version](https://user-images.githubusercontent.com/50232392/117990364-668fa900-b33d-11eb-8edb-f95eaf4784ee.png)
![git_clone](https://user-images.githubusercontent.com/50232392/117990366-67283f80-b33d-11eb-95a3-bcabe31fc583.png)

![php_composer](https://user-images.githubusercontent.com/50232392/117990413-70b1a780-b33d-11eb-8986-a2130d7a9598.png)


i don't know what the problem is

**Comment by Alfr3d** [comment]
@MLK57  Thanks!
Can youchange composer.json file content:
`{
    "name": "invertus/saferpay",
    "type": "project",
    "description": "Saferpayofficial module for Prestashop",
    "autoload": {
        "psr-4": {
            "Invertus\\SaferPay\\": "src/"
        },
        "classmap": [
            "src/Entity"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Invertus\\SaferPay\\Tests\\": "tests/"
        }
    },
    "require": {
        "php": ">=5.6",
        "vlucas/phpdotenv": "^3.6",
        "symfony/expression-language": "^3.4",
        "symfony/config": "^3.4",
        "symfony/dependency-injection": "^3.4",
        "symfony/filesystem": "^3.4",
        "guzzlehttp/guzzle": "^5.3.3",
        "symfony/yaml": "^3.4"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "*",
        "invertus/integrationtestsuite": "dev-master",
        "phpunit/phpunit": "*",
        "behat/behat": "*",
        "symfony/translation": "*"
    },
    "scripts": {
        "test-integration": "./vendor/bin/phpunit --configuration ./tests/Integration/phpunit.xml",
        "test-unit": "./vendor/bin/phpunit --configuration tests/Unit/phpunit.xml"
    },
    "config": {
        "prepend-autoloader": false,
        "platform": {
            "php": "5.6"
        }
    },
    "author": "PrestaShop",
    "license": "AFL-3.0"
}
`
and try again ? :)

**Comment by Alfr3d** [comment]
@MLK57  Thanks!
Can you change composer.json file content to :
`{
    "name": "invertus/saferpay",
    "type": "project",
    "description": "Saferpayofficial module for Prestashop",
    "autoload": {
        "psr-4": {
            "Invertus\\SaferPay\\": "src/"
        },
        "classmap": [
            "src/Entity"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Invertus\\SaferPay\\Tests\\": "tests/"
        }
    },
    "require": {
        "php": ">=5.6",
        "vlucas/phpdotenv": "^3.6",
        "symfony/expression-language": "^3.4",
        "symfony/config": "^3.4",
        "symfony/dependency-injection": "^3.4",
        "symfony/filesystem": "^3.4",
        "guzzlehttp/guzzle": "^5.3.3",
        "symfony/yaml": "^3.4"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "*",
        "phpunit/phpunit": "*",
        "behat/behat": "*",
        "symfony/translation": "*"
    },
    "scripts": {
        "test-integration": "./vendor/bin/phpunit --configuration ./tests/Integration/phpunit.xml",
        "test-unit": "./vendor/bin/phpunit --configuration tests/Unit/phpunit.xml"
    },
    "config": {
        "prepend-autoloader": false,
        "platform": {
            "php": "5.6"
        }
    },
    "author": "PrestaShop",
    "license": "AFL-3.0"
}
`
and try run "composer install --no-dev --optimize-autoloader" command again ? :)

**Comment by MLK57** [comment]
Hey ! It's better :) but i have still one exception... IS that bad to upload the module with this error ???

**Comment by MLK57** [comment]
Hey ! It's better :) but i have still one exception... IS that bad to upload the module with this error ???
![ok_with_error](https://user-images.githubusercontent.com/50232392/118274048-f57afd80-b4c4-11eb-8e65-9e20ad8e4184.png)

**Comment by MLK57** [comment]
It's better ! It's ok now ! thanks a lot

**Comment by SimonasB88** [comment]
@MLK57 great news!

Can we serve something else regarding this case or we can close the ticket now?

--
Best Regards
Invertus Support Team

**Comment by Saimis777** [comment]
Hi,

Due to inactivity we will close this issue for now.

Let us know if further help is needed!

--
Best regards,
Invertus Support team
