### ISSUE TITLE
No invoices for payments by Visa or Mastercard

### ISSUE THREAD

**Issue by brunostuder** [Invertus/saferpayofficial#23]
Hello,

We have a issue with the invoice generation, it works well but the **invoices are not generated when user paid with Visa or Mastercard**.

<img width="717" alt="Capture d’écran 2021-05-20 à 16 00 33" src="https://user-images.githubusercontent.com/59470758/119114679-a6821a80-ba26-11eb-8b94-8006ee7f9f3d.png">

Please see attachement.

Best,

**Comment by Saimis777** [comment]
Hi @brunostuder !

Thank you for your message, we'll check with the issue internally, and get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @brunostuder ,

As this is a duplicate with the newer raised issue, could you clarify if by following the video it helped with the invoice generation? 

The video of how to enable invoices - https://ufile.io/08q189cm

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi,

Due to inactivity we will close this issue for now.

Please let me know if you have any further questions, or need help, we would gladly help you out!

Have a nice day!

--
Best regards,
Invertus Support team
