### ISSUE TITLE
Unable to Composer Install

### ISSUE THREAD

**Issue by brunostuder** [Invertus/saferpayofficial#24]
Hi,

I tried to download the new version of the plugin but it's impossible for me to do the composer update command, I've an error coming. 

_dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.62.dylib
  Referenced from: /usr/local/bin/php
  Reason: image not found
Abort trap: 6_

After 1h30 trying to solve this issue, I write you to ask you a full package of the plugin that doesn't require "composer install".

Thank you for your quick reply,

Best,

**Comment by Saimis777** [comment]
Hey Bruno,

Could you try this .zip file here?

I've created a download link for the zip file - https://ufile.io/zvrx70lv

Let me know how it will go!

--
Best regards,
Invertus Support taem

**Comment by brunostuder** [comment]
Hi,

Thank you, I successfully installed the plugin.

Good:

- Now TWINT and MASTERCARD payments are well captured automatically, not only AUTHORIZED, thank's a lot.

Not good:

- Fee issues, will add messages in the already open ones and open new ones for the others things

Best,

**Comment by brunostuder** [comment]
Close issue
