### ISSUE TITLE
Can you help me out with translations

### ISSUE THREAD

**Issue by ZZizy** [Invertus/saferpayofficial#243]
v1.2.3 here. As far as I know, there is no easy way to translate the order fields that are used for the subject for the emails.

I know this may be confusing, so let me break it down. 
The order state/ order status named Payment completed by Saferpay, and others, but manly this one, is used in PrestaShop as subject when sending emals. And as far as I have tried finding the field to translate it to a different language, there is no possible way to do so in PrestaShop environment.

**Comment by ZZizy** [comment]
The other bug report would be that & is saved as &amp;
This might be fixed in 1.2.5.
If not here is the brakedown:
in the saferpay module settings (any field like name or passowrd) & is stored in it as &amp; this is saved correctly only the first time.
If you go back to the settings after saving, & turns into &amp; This is probably because of how it reads and formats the text. So saving the second time saves &amp; instead. Witch is just annoying trying to updating something, and then you can't login into the service, because you did not notice your password changing.

**Comment by justelis22** [comment]
Hi there, @ZZizy, Happy New Year!

Yes, the mentioned issue is fixed in the 1.2.5 version.

There is a beta version available if you would like to get it sooner.

If you have any questions, please let me know!

Best Regards,
Invertus Support team.
