### ISSUE TITLE
Unable to REFUND directly from the back office

### ISSUE THREAD

**Issue by brunostuder** [Invertus/saferpayofficial#25]
Hi,

With the new version of the plugin you sent me I successfully CAPTURED the Twint and Visa payments automatically but now I can't REFUND directly from the back-office of prestashop:

<img width="269" alt="Capture d’écran 2021-05-26 à 11 36 37" src="https://user-images.githubusercontent.com/59470758/119638900-64d2e480-be17-11eb-90dd-2b24a40f221e.png">

Best,

**Comment by Saimis777** [comment]
Hey,

Could you please give us the full steps of issue reproduction? As we could not replicate this from our end.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi again @brunostuder ,

We tested refund functionality on newly installed module from Github and looks like it works fine. Are you refunding payments with saferpayofficial block? 

You can find this block in Orders → Orders → single order → SaferPayOfficial block.

![image](https://user-images.githubusercontent.com/75423142/120188648-0ba3f000-c21f-11eb-8fdb-8445960fa7f3.png)
![image](https://user-images.githubusercontent.com/75423142/120188669-1068a400-c21f-11eb-93fa-f38db1a2f2ad.png)



--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi,

Due to inactivity we will close this issue for now.

Please let me know if you have any further questions, or need help, we would gladly help you out!

Have a nice day!

--
Best regards,
Invertus Support team
