### ISSUE TITLE
Invoice and Delivery slip are not generated or available

### ISSUE THREAD

**Issue by brunostuder** [Invertus/saferpayofficial#26]
Hi,

With the new version of the plugin you sent me I successfully CAPTURED the Twint and Visa payments automatically but still have an other issue:

When order are paid with your plugin I'm unable to download invoice or delivery slip (order states are well setted up in my backend...).

Please see attachment.

Best,

<img width="695" alt="Capture d’écran 2021-05-26 à 11 36 26" src="https://user-images.githubusercontent.com/59470758/119639169-a3689f00-be17-11eb-975d-b6b6864c5413.png">

**Comment by Saimis777** [comment]
Hi,

Please check if your “Order settings → statuses (invoice checkbox enabled for used statuses)“.

Here's a video attached of how to enable invoices for better understanding - https://ufile.io/08q189cm 

Let me now if you have any further questions!

--
Best regards,
Invertus Support team

**Comment by brunostuder** [comment]
Hello,

Thank's for your reply.

The order states are well setted up... 

<img width="998" alt="Capture d’écran 2021-06-02 à 10 10 45" src="https://user-images.githubusercontent.com/59470758/120447432-e0d6aa80-c38a-11eb-94dc-1ed1367ac60b.png">

Best,

**Comment by brunostuder** [comment]
Is it possible to send me the new update of the plugin in Zip file installable in prestashop, because I've an issue with the composer command on my mac...

Best,

**Comment by Saimis777** [comment]
Hey @brunostuder ,

Sure, I've uploaded the module here - https://ufile.io/78xu0qsg

Let me know if you need further help!

--
Best regards,
Invertus Support team

**Comment by brunostuder** [comment]
Hi,

Thank you for your reactivity.

I've installed the new update but still, I can't get invoices and still I can't refund orders directly from Prestashop Backend...


Best,

**Comment by Saimis777** [comment]
@brunostuder 

Are you running any other payment modules apart from Saferpay? Also did you follow the video guide to enable the invoices?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @brunostuder ,

Do you need any further help regarding this case?

Let me know!

--
Best regards,
Invertus Support team

**Comment by brunostuder** [comment]
Hey,

This issue is still not solved.

No I'm not using other payments plugins.

Is it possible to find a fix to generated these invoice and delevery slip please.

Best,

**Comment by Saimis777** [comment]
Hi @brunostuder ,

We could not replicate the issue from our end, the video I've provided before, did you follow the steps? If they did not help, we would need your BO + FTP credentials for further investigation, could you send them to - support@invertus.eu?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @brunostuder ,

Just confirming that we've received the credentials, I've forwarded the information to the developer, also can we create test products on your shop for invoice generation testing?  and we will get back to you as soon as possible!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @brunostuder ,

Could you check if you could enable the same credentials as provided in the email for us to log in? 

As at the moment they stopped working.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
@brunostuder - we have updated you via email. Module is also updated in repository.

I guess we will close this ticket, once we get the feedback from community.


Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
Case closed, due to the successful fix. 
Other related issues should be raised by new ticket.

Best regards,
Invertus Support Team
