### ISSUE TITLE
How to change the text "PrestaShop payment"

### ISSUE THREAD

**Issue by yvannb** [Invertus/saferpayofficial#28]
Hello,

How can I change the text "PrestaShop payment" on Saferpay payment page or on the payement tab on Apple Pay ? Is it possible to add custom text or order id or something else ?

Thank you and have a nice day

![2021-06-08 23_40_41-Window](https://user-images.githubusercontent.com/80780017/121261537-26c3cf00-c8b3-11eb-8303-ff03d858e99c.png)

**Comment by Saimis777** [comment]
Hey!

Thank you for your message!

To change that tab, you would need custom development, as it's not really configurable by simply changing it, you would need to enter the code to do that. 

Let me know if you have any further questions!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi,

Due to inactivity we will close this issue for now.

Please let me know if you have any further questions, or need help, we would gladly help you out!

Have a nice day!

--
Best regards,
Invertus Support team
