### ISSUE TITLE
When customer click cancel, redirected to webstite with a success confirmation 1.0.10 version

### ISSUE THREAD

**Issue by powolnymarcel** [Invertus/saferpayofficial#40]
Hi,

When the customers clicks on pay and is being redirected to SaferPay website and then click "Cancel" he is being redirected to the merchant website with a successful message and the cart is emptied.

I tried the 1.0.10 version

Any help on this behaviour would be appreciated :)

**Comment by SimonasB88** [comment]
Hey @powolnymarcel 

Thanks for your insights. 
Passed your information to the team, we will keep you posted referring this case.

Best Regards
Invertus Support Team

**Comment by Saimis777** [comment]
hi @powolnymarcel ,

As we've received information from Saferpay team, it is an issue from their end, and the ticket is already raised for their developers, I've asked them to get in touch with you when it will be resolved, if they will not, please contact them again to follow up on this case.

Thank you for your understanding, and let us know if you have any more questions!

--
Best regards,
Invertus Support team
