### ISSUE TITLE
Not working new addon update

### ISSUE THREAD

**Issue by powolnymarcel** [Invertus/saferpayofficial#43]
Hello,

We have just installed the new version, followed the readme tutorial, the addon is installed but not working as it doesn't show any payment method. Can you help ?

I can't see the SaferPay submenu
![image](https://user-images.githubusercontent.com/12711039/132051802-06348d6f-83ad-4e50-97d2-3aa28633168d.png)

The addon is installed:
![image](https://user-images.githubusercontent.com/12711039/132051871-d9f9fba6-6669-4488-995c-f9c2b049a4e3.png)

![image](https://user-images.githubusercontent.com/12711039/132053322-3d3ee58c-1ea6-40eb-a55b-28859fea9e3d.png)

**Comment by powolnymarcel** [comment]
This might be related

![image](https://user-images.githubusercontent.com/12711039/132055847-e596ae4f-67c7-43c0-9d86-cd6d8393000b.png)

**Comment by powolnymarcel** [comment]
By the way we have 1.7.5 PS

is it not compatible ?

**Comment by Saimis777** [comment]
Hi @powolnymarcel ,

Thank you for your message!

Could you clarify if you've tried resetting the module? And which PHP version you are running? Did you download the module from GitHub or addons marketplace?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by powolnymarcel** [comment]
Hi, 
thanks for responding ;)

I have completely uninstalled the module and re installed the module from github and rigorously followed your tutorial.  The latest version is not on the marketplace yet (as I checked several days ago). Tested on PHP 7.4 and 8.0

**Comment by Saimis777** [comment]
Hi @powolnymarcel 

Maybe you could send us your BO+FTP credentials to - support@invertus.eu for further investigation?

Just be sure not to send them as a reply in GitHub.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @powolnymarcel ,

Do you still need assistance? Or everything is working?

Let us know!

--
Best regards,
Invertus Support team

**Comment by powolnymarcel** [comment]
Hi, sent you an email right now. Thanks for caring :)

**Comment by Saimis777** [comment]
Thanks @powolnymarcel for the nice feedback!

Let us know if you'll need any help!

--
Best regards,
Invertus Support team
