### ISSUE TITLE
issue with cart disappearance after customer hit return button in browser

### ISSUE THREAD

**Issue by powolnymarcel** [Invertus/saferpayofficial#46]
Hello,

We have an issue with the cart. 

When the customer is being redirected to the payment provider and clicks "cancel" he is taken back to the shop with the previous content of his cart. That's OK but if instead of clicking "cancel" he clicks "return" in the browser the cart is cleared

tested on the 1.0.13 version in PS 1.7.4

**Comment by powolnymarcel** [comment]
Hello,

Tested you last update, we still have this issue.

The customer clicks to pay, is redirected to Saferpay to pay his order, hit back button and cart is empty

**Comment by Saimis777** [comment]
Hi @powolnymarcel ,

As we spoke via email, we will investigate this further, and update this issue.

--
Best regards,
Invertus Support team

**Comment by powolnymarcel** [comment]
Yes thank you :). Thanks for all updates you made recently
