### ISSUE TITLE
Saferpay Transaction != Autorisation

### ISSUE THREAD

**Issue by powolnymarcel** [Invertus/saferpayofficial#58]
Hello,

When a customer chooses to pay with a credit card (VISA or MasterCard) the right payload seems to be sent to Saferpay

<img width="527" alt="image" src="https://user-images.githubusercontent.com/12711039/175276440-e9917cd2-e633-41be-827c-94a287a510e9.png">

But Saferpay make a TRANSACTION on the amount without the delivery fees ?

Why ?

My colleague tells me that in 'SaferPayOrderStatusService.php' you base the total price on the total price of the cart but the cart doesn't know the total real paid 

we changed 
        $totalPrice = $cartDetails['total_price'] * SaferPayConfig::AMOUNT_MULTIPLIER_FOR_API;
TO
       $totalPrice = $order->**total_paid_real** * SaferPayConfig::AMOUNT_MULTIPLIER_FOR_API;

[saferpayofficial](https://github.com/Invertus/saferpayofficial)/[src](https://github.com/Invertus/saferpayofficial/tree/master/src)/[Service](https://github.com/Invertus/saferpayofficial/tree/master/src/Service)/SaferPayOrderStatusService.php

**Comment by powolnymarcel** [comment]
Any help guys :) ?

**Comment by justelis22** [comment]
Hey there, @powolnymarcel! Sorry for the delay.

We have received your query, and it will be checked. Once we have some updates, we will let you know.

Best Regards,
Invertus Support team.

**Comment by powolnymarcel** [comment]
OK thank you :)

**Comment by justelis22** [comment]
@powolnymarcel,

Could you please let us know which PS version are you using?

Best Regards,
Invertus Support team.

**Comment by powolnymarcel** [comment]
1.7.8.6

**Comment by justelis22** [comment]
Hello, @powolnymarcel!

Our team has managed to identify the issue and it is already fixed, we will test everything out this week and upload the new release of this module :)

Thanks for waiting! 

Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hey, @powolnymarcel!

A new release with a fix was already uploaded to Addons Marketplace. You can upgrade the module, and everything should be working just fine!

We will be waiting for your feedback! For now, we will mark this issue as resolved, if anything comes up, don't hesitate to reopen it.

Best Regards,
Invertus Support team.
