### ISSUE TITLE
New certificate for Saferpay - is version 1.0.21 compatible with Worldline request

### ISSUE THREAD

**Issue by baden32** [Invertus/saferpayofficial#96]
We just received the following message/info from Saferpay/Worldline and I would like to know if the latest version of the plugin saferpayofficial (1.0.21) is compatible/ok for these new requirements:

Dear,

At Worldline, the security of our merchants is our top priority. This is why we constantly adapt our products and services to the latest safety standards in force. In this context, we are providing a new certificate for our payment solution Saferpay, which can be used for all services in the future.

What should you do ?
Please ensure that your system accepts this new certificate no later than March 22, 2023 in order to allow communication with the Saferpay system.

Please also consult the online FAQs, which will provide you with additional information regarding this change.

If some doubts remain as to possible modifications to be made on your system, we recommend that you contact the technical operator or the administrator of your system.

Cordially,
Your Worldline team

Thank you in advance for your help/reply.
Regards
Joel

**Comment by justelis22** [comment]
Hey there @baden32,

We will be glad to help you with this! Our team will check your case, and get back to you as soon as possible with an update.

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @baden32,

We have communicated with the SaferPay integration team and they mentioned that this should not affect the module itself. Everything will work as it was.

I am going to mark this issue as resolved, but if you have any questions, let us know!

-
Best Regards,
Invertus Support team.

**Comment by baden32** [comment]
Great, thenks for your feedback and the info.
Issu can be closed.
Regards
